FROM node:18-alpine as build

WORKDIR /app

RUN npm install -g pnpm

COPY pnpm-workspace.yaml .
COPY package.json .
COPY packages/frontend ./packages/frontend

RUN pnpm install

RUN cd packages/frontend && pnpm run build

FROM node:18-alpine

WORKDIR /app

RUN npm install -g serve

COPY --from=build /app/packages/frontend/dist ./dist

EXPOSE 3000

CMD ["serve", "-s", "dist", "-l", "3000"]
